version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  postgresServerDb:
    container_name: container-postgres
    image: postgres:latest
    ports:
      - "5022:5432"
    environment:
      - POSTGRES_USER=user_1
      - POSTGRES_PASSWORD=pass_123
      - POSTGRES_DB=androidDb
    networks:
      - myAppNetwork
    volumes:
#       - d:/web/pd322/postgresql:/var/lib/postgresql/data  # Use the volume name msvol here
        - /data/postgresql/data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  app:
    container_name: android_api_container
    image: sashok9203/my_android_api:latest
    ports:
      - "5088:8080"
    networks:
      - myAppNetwork
    depends_on:
      - postgresServerDb
    volumes:
      - /volumes/aspnet/uploading:/app/uploading   # Use the volume name appvol here
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
  
  
